#WAP TO STORE 7 FRUITS IN A TUPLE AND PRINT THE TUPLE
list = []
f1 = input("Enter fruit name: ")
list.append(f1)
f2 = input("Enter fruit name: ")
list.append(f2)
f3 = input("Enter fruit name: ")
list.append(f3)
f4 = input("Enter fruit name: ")
list.append(f4)
f5 = input("Enter fruit name: ")
list.append(f5)
f6 = input("Enter fruit name: ")
list.append(f6)
f7 = input("Enter fruit name: ")
list.append(f7)
print(list)