numbers = [ 1, 2, 3, 4, 5]
print('Max:', max(numbers))
print('Min:', min(numbers))
print('Sum:', sum(numbers))
print('Len:', len(numbers))
print('All:', all(numbers))
print('All:', all([1, 2, 3]))
print('All:', all([1, 2, 3, 0]))
print('All:', all(['a', 'b', 'c']))
print('All:', all(['a', 'b', '']))
print('Any:', any(['', '', '']))
print('All:', all([0, 0, 0, 0]))
print('Count:', numbers.count(5))
print('Index at :', numbers.index(3))